---

- name: API Login to UCSM and collect device claim info (for use by Intersight)
  hosts: "{{ group | default('cisco_hx_fi') }}"
  connection: local
  collections: 
    - cisco.ucs
  gather_facts: false
  vars:
  vars_files:
  tasks:
    - name: Login into UCSM
      include_tasks: 10_ucsm_api_login.yml
      tags: [ucsm_api_login]
    - name: Configure uplinks to datacenter fabric
      vars: 
        # port_channel_list:
        #   - name: "PC11-Switch_103"
        #     pc_id: '11'
        #     fabric_id: "A"
        #     slot_id: '1'
        #     port_id: '31'
        #     admin_speed: "auto"
        #   - name: "PC11-Switch_104"
        #     pc_id: '11'
        #     fabric_id: "A"
        #     slot_id: '1'
        #     port_id: '32'
        #     admin_speed: "auto"
        #   - name: "PC12-Switch_103"
        #     pc_id: '12'
        #     fabric_id: "B"
        #     slot_id: '1'
        #     port_id: '31'
        #     admin_speed: "auto"
        #   - name: "PC12-Switch_104"
        #     pc_id: '12'
        #     fabric_id: "B"
        #     slot_id: '1'
        #     port_id: '32'
        #     admin_speed: "auto"
      include_tasks: 17_ucsm_configure_uplink_pc.yml
      # tags: [never]






