---

- name: Define anchor for Intersight API login info 
  block:
    - set_fact:
        intersight_api_login_info: &intersight_api_login_info
          api_private_key:    "{{ intersight_api_private_key }}"
          api_key_id:         "{{ intersight_api_key_id }}"
          api_uri:            "{{ intersight_api_uri | default(omit) }}"
          validate_certs: "{{ intersight_validate_certs | default(omit) }}"
          #state:          "{{ intersight_state | default(omit) }}"
    - debug:
        msg: "API Info is: {{ intersight_api_login_info }} and Cluster Name is {{ hx_cluster_profile_name }}"


- name: Validate Cluster Configuration before deployment
  vars:
  intersight_rest_api:
    <<: *intersight_api_login_info
    resource_path: /hyperflex/ClusterProfiles
    query_params:
      $filter: "Name eq '{{ hx_cluster_profile_name }}'"
    api_body: {
      "Action": "Validate"
    }
    state: present
  register: validation_response
# - name: Save Validation Status
#   set_fact:
#     "validation_status: {{ validation_response}}.XXXX"

  # when:
  #   - profile.api_response.ConfigContext.ConfigState != 'Configuring'
  #   - profile.api_response.ConfigContext.ConfigState != 'Associated'
# Can optionally wait for subsequent tasks if needed
# register: result
# until: result.api_response.config_context.config_state == 'Associated'
# retries: 20
# delay: 30
- debug: 
    msg: "Successfully triggered validation of cluster configuration for deployment. Please wait for it to complete. It typically takes 13-15min "
