---

- name: Define anchor for UCSM API login info 
  set_fact:
    ucsm_api_login_info: &ucsm_api_login_info
      hostname: "{{ inventory_hostname }}"
      username: "{{ ucsm_username | default('admin') }}"
      password: "{{ ucsm_password | default('cisco123') }}"
      state:    "{{ ucsm_state | default(omit) }}"

- debug:
    msg: "UCSM API Info: {{ucsm_api_login_info}}"

- name: API Login to UCSM
  block:
    - name: Login into UCSM
      vars: 
       #test : "1"
      ansible.builtin.uri:
        url: "https://{{ hostname }}/nuova"
        method: POST
        headers: 
          Content-Type: application/x-www-form-urlencoded
        body: <aaaLogin inName='{{username}}' inPassword='{{password}}'></aaaLogin>
        body_format: form-urlencoded
        #status_code: 200
        return_content: yes
        #timeout: 60
        validate_certs: no
      register: login_response
    - debug:
        msg: "{{ login_response.content }}"
    - name: Get cookie from xml response
      # pip install lxml required 
      xml:
        xmlstring: "{{ login_response.content }}"
        content: "attribute"
        xpath: /aaaLogin
      register: xmlattribute

    - name: Show an attribute value
      debug:
        var: xmlattribute.matches[0].aaaLogin.outCookie

    - name: Set cookie var
      set_fact:
        cookie_fact: "{{ xmlattribute.matches[0].aaaLogin.outCookie | string }}"

    - name: check variable data type
      debug:
        msg: "{{ cookie_fact | type_debug }}"

    - name: Register dummy host with variable
      add_host:
        name: "DUMMY_HOST"
        ucsm_cookie: "{{cookie_fact}}"
  vars:
    <<: *ucsm_api_login_info

    