---

#-------------------------------------------------------------------------------------
#  Validate HyperFlex Standard Cluster Configuration/Profile 
#-------------------------------------------------------------------------------------

- name: Define anchor for Intersight API login info 
  set_fact:
    intersight_api_login_info: &intersight_api_login_info
      api_private_key:          "{{ intersight_api_private_key }}"
      api_key_id:               "{{ intersight_api_key_id }}"
      api_uri:                  "{{ intersight_api_uri | default(omit) }}"
      validate_certs:           "{{ intersight_validate_certs | default(omit) }}"
      state:                    "{{ intersight_state | default(omit) }}"

- name: Validate Cluster Configuration before deployment
  vars:
  intersight_rest_api:
    <<: *intersight_api_login_info
    resource_path: /hyperflex/ClusterProfiles
    query_params:
      $filter: "Name eq '{{ hx_cluster_profile_name }}'"
    api_body: {
      "Action": "Validate"
    }
    state: present
  register: validation_response

- name: Print status of validation request
  debug: 
    msg: "Successfully triggered validation of cluster configuration for deployment. Please wait for it to complete. It typically takes 13-15min "
#-----------------------------------------------------------------------------------------