---

#-------------------------------------------------------------------------------------
#  Create HyperFlex Cluster System Config Policy
#-------------------------------------------------------------------------------------

- name: Define anchor for Intersight API login info 
  set_fact:
    intersight_api_login_info: &intersight_api_login_info
      api_private_key:         "{{ intersight_api_private_key }}"
      api_key_id:              "{{ intersight_api_key_id }}"
      api_uri:                 "{{ intersight_api_uri | default(omit) }}"
      validate_certs:          "{{ intersight_validate_certs | default(omit) }}"
      state:                   "{{ intersight_state | default(omit) }}"
  run_once: true

- name: Create HyperFlex System Config Policy and return Moid
  intersight_rest_api:
    <<: *intersight_api_login_info
    resource_path: /hyperflex/SysConfigPolicies
    query_params:
      $filter: "Name eq '{{ hx_sys_config_policy_name }}'"
    api_body: {
      "Organization": {
        "Moid":           "{{ organization_moid }}"
      },
      "Name":             "{{ hx_sys_config_policy_name }}",
      "Timezone":         "{{ hx_sys_config_timezone }}",
      "DnsServers":       "{{ hx_sys_config_dns_servers }}",
      "NtpServers":       "{{ hx_sys_config_ntp_servers }}",
      "DnsDomainName":    "{{ hx_sys_config_dns_domain }}",
      "ClusterProfiles": [
        {
        "Moid":           "{{ hx_cluster_profile_moid }}"
        }
      ]
    }
    state: present
  register: hx_sys_config_policy_response
  run_once: true
  delegate_to: local_host
  tags: 
    - hx_sys_config_policy
    - never
    #- never, debug, always

- name: Query for an existing HyperFlex System Config Policy and return Moid
  intersight_rest_api:
    <<: *intersight_api_login_info
    resource_path: /hyperflex/SysConfigPolicies
    query_params:
      $filter: "Name eq '{{ hx_sys_config_policy_name }}'"
    state: present
  register: hx_sys_config_policy_response
  run_once: true
  delegate_to: local_host
  tags: 
    - hx_sys_config_policy


- name: Moid for HyperFlex System Config Policy
  set_fact:
    hx_sys_config_policy_moid: "{{ hx_sys_config_policy_response.api_response.Moid }}"
  run_once: true

- name: Print status of 'Create HyperFlex Cluster System Config' policy
  debug:
    msg: "Created HyperFlex System Config Policy '{{ hx_sys_config_policy_name }}' with Moid: '{{ hx_sys_config_policy_moid }}'"  
  #tags: [never, debug, always]
  #-----------------------------------------------------------------------------------------