---

#-------------------------------------------------------------------------------------
#  Query UCSM for Device Connector status and save status (for e.g. Claimed)
#-------------------------------------------------------------------------------------

- name: Query UCSM for Device Connector status 
  block:
    - name: Get Device Connector Status
      ansible.builtin.uri:
        url: "https://{{ inventory_hostname }}/connector/Systems"
        method: GET
        headers:
          Content-Type: application/json
          Ucsmcookie: "ucsm-cookie={{ hostvars['DUMMY_HOST']['ucsm_cookie'] }}"
        return_content: yes
        validate_certs: no
      register: response
      tags: ucsm_device_connector_status

    - name: Print response to Get UCSM Device Connector status 
      debug: 
        msg: "Response from Get UCSM Device Connector status is: {{ response.content }}"
        #msg: "Response from Get UCSM Device Connector status is: {{ response.json[0].AccountOwnershipState }}"
      #tags: [never, debug, always, ucsm_device_connector_status]
      tags: always


    - name: Set Device Connector status 
      ansible.builtin.set_fact:
        #ucsm_device_connector_status_fact: "{{ response.content | from_json }}"
        ucsm_device_connector_status_fact: "{{ response.content }}"
      tags: ucsm_device_connector_status


    # # (Option-1)
    # - name: Save Device Connector Status using a variable
    #   ansible.builtin.set_fact:
    #     ucsm_device_connector_status: "{{ ucsm_device_connector_status_fact[0]['AccountOwnershipState'] }}"
    #     #ucsm_device_connector_status: "{{ response.json[0].AccountOwnershipState }}"
    #   tags: ucsm_device_connector_status

    # - name: Print UCSM Device Connector Status - saved
    #   debug: 
    #     msg: "Device Connector Status on Cisco UCSM is: {{ ucsm_device_connector_status }}"
    #   #tags: [never, debug, always, ucsm_device_connector_status]
    #   tags: always

    # (Option-2) - If using this, all subsequent calls to ucsm_device_connector_status should use
    # the following: hostvars['DUMMY_HOST']['ucsm_device_connector_status'].
    # This is also necessary when carrying over this variable to a different host (for e.g. to Intersight)
    - name: Save Device Connector Status by registering it with a dummy host
      ansible.builtin.add_host:
        name: "DUMMY_HOST"
        ucsm_device_connector_status: "{{ ucsm_device_connector_status_fact[0]['AccountOwnershipState'] }}"
        #ucsm_device_connector_status: "{{ response.json[0].AccountOwnershipState }}"
      tags: ucsm_device_connector_status

    - name: Print UCSM Device Connector Status - Variable assigned to Dummy Host
      debug:
        msg: "Device Connector Status on Cisco UCSM is: {{ hostvars['DUMMY_HOST']['ucsm_device_connector_status'] }}"
      #tags: [never, debug, always, ucsm_device_connector_status]
      tags: always

#-------------------------------------------------------------------------------------
