---

#-------------------------------------------------------------------------------------
#  Enable UCSM Device Connector if it is not already claimed in Intersight
#-------------------------------------------------------------------------------------

- name: Enable UCSM Device Connector if it is not already claimed
  block: 
    - name: Enable device connector 
      ansible.builtin.uri:
        url: "https://{{ inventory_hostname }}/connector/Systems"
        method: PUT
        headers:
          Content-Type: application/json
          Ucsmcookie: "ucsm-cookie={{ hostvars['DUMMY_HOST']['ucsm_cookie'] }}"
        body: "{\"AdminState\": true}"
        status_code: 200
        return_content: yes
        validate_certs: no
      register: response
      tags: ucsm_enable_device_connector
      
    - name: Print response from enabling Device Connector on UCSM
      debug: 
        msg: "Response from enabling Device Connector is: {{ response.content }}"
      #tags: [never, debug, always, ucsm_enable_device_connector]
      tags: always

    - name: Pause to allow enough time for enabling Device Connector 
      pause:
        seconds: 30
      tags: ucsm_enable_device_connector

    - name: Set status of enabling Device Connector
      ansible.builtin.set_fact:
        enable_device_connector_fact: "{{ response.content }}"
      tags: ucsm_enable_device_connector
    
    - name: Save status of enabling Device Connector
      ansible.builtin.set_fact:
        enable_device_connector_status: "{{ enable_device_connector_fact[0]['AccountOwnershipState'] }}"
        #enable_device_connector_status: "{{ response.json[0].AccountOwnershipState }}"
      tags: ucsm_enable_device_connector
    
    - name: Verify it enabled successfully
      debug:
        msg: "Successfully enabled Device Connector"
      when: enable_device_connector_status == "Claimed"

  # --- multiple options---
  #when: ucsm_device_connector_status != "Claimed"
  when: hostvars['DUMMY_HOST']['ucsm_device_connector_status'] != "Claimed"
  #-------------------------------------------------------------------------------------

    
