---

#-------------------------------------------------------------------------------------
#  Get Claim Code if UCSM is not already claimed in Intersight
#-------------------------------------------------------------------------------------

- name: Get Claim Code from UCSM
  block:
    - name: Get Claim Code
      uri:
        url: "https://{{ inventory_hostname }}/connector/SecurityTokens"
        method: GET
        headers:
          Content-Type: application/json
          Ucsmcookie: "ucsm-cookie={{ hostvars['DUMMY_HOST']['ucsm_cookie'] }}"
        status_code: 200
        return_content: yes
        validate_certs: no
      register: response
      tags: ucsm_claim_code
    
    - name: Print response to Get Claim Codefrom UCSM 
      debug: 
        msg: "Response from Get Claim Code is: {{ response.content }}"
      #tags: [never, debug, always, ucsm_claim_code]
      tags: always


    - name: Set Claim Code
      ansible.builtin.set_fact:
        ucsm_device_id_fact: "{{ response.content }}"
      tags: ucsm_claim_code


    - name: Save Claim Code variable
      ansible.builtin.set_fact:
        ucsm_claim_code: "{{ ucsm_claim_code_fact[0]['Token'] }}"
        #ucsm_claim_code: "{{ response.json[0].Token }}"
      tags: ucsm_claim_code

    - name: Print UCSM Claim Code
      debug: 
        msg: "UCSM Claim Code is: {{ ucsm_claim_code}}"
      #tags: [never, debug, always, ucsm_claim_code]
      tags: always
  
  # --- multiple options---
  #when: ucsm_device_connector_status != "Claimed"
  when: hostvars['DUMMY_HOST']['ucsm_device_connector_status'] != "Claimed"
  #-------------------------------------------------------------------------------------

  
    







