---

#-------------------------------------------------------------------------------------
#  Create HyperFlex Cluster vCenter Config Policy
#-------------------------------------------------------------------------------------

- name: Define anchor for Intersight API login info 
  set_fact:
    intersight_api_login_info: &intersight_api_login_info
      api_private_key:         "{{ intersight_api_private_key }}"
      api_key_id:              "{{ intersight_api_key_id }}"
      api_uri:                 "{{ intersight_api_uri | default(omit) }}"
      validate_certs:          "{{ intersight_validate_certs | default(omit) }}"
      state:                   "{{ intersight_state | default(omit) }}"
  run_once: true

- name: Create HyperFlex vCenter Config Policy and return Moid
  intersight_rest_api:
    <<: *intersight_api_login_info
    resource_path: /hyperflex/VcenterConfigPolicies
    query_params:
      $filter: "Name eq '{{ hx_vcenter_config_policy_name }}'"
    api_body: {
      "Organization": {
        "Moid":         "{{ organization_moid }}"
      },
      "Name":             "{{ hx_vcenter_config_policy_name }}",
      "Hostname":         "{{ hx_vcenter_hostname }}",
      "Username":         "{{ hx_vcenter_username }}",
      "Password":         "{{ hx_vcenter_password | default(omit) }}",
      "DataCenter":       "{{ hx_vcenter_datacenter }}",
      "ClusterProfiles": [
        {
        "Moid":           "{{ hx_cluster_profile_moid }}"
        }
      ]
    }
    state: present
  register: hx_vcenter_config_policy_response
  run_once: true
  delegate_to: local_host
  tags: 
    - hx_vcenter_config_policy
    - never
    #- never, debug, always
    
- name: Query for an existing HyperFlex vCenter Config Policy and return Moid
  intersight_rest_api:
    <<: *intersight_api_login_info
    resource_path: /hyperflex/VcenterConfigPolicies
    query_params:
      $filter: "Name eq '{{ hx_vcenter_config_policy_name }}'"
    state: present
  run_once: true
  register: hx_vcenter_config_policy_response
  delegate_to: local_host
  tags: 
    - hx_vcenter_config_policy



- name: Moid for HyperFlex vCenter Config Policy
  set_fact:
    hx_vcenter_config_policy_moid: "{{ hx_vcenter_config_policy_response.api_response.Moid }}"
  run_once: true

- name: Print status of 'Create HyperFlex Cluster vCenter Config' policy
  debug:
    msg: "Created HyperFlex vCenter Config Policy '{{ hx_vcenter_config_policy_name }}' with Moid: '{{ hx_vcenter_config_policy_moid }}'"  
  #tags: [never, debug, always]

#-----------------------------------------------------------------------------------------
