---

- name: Query to get Device Connector status from Cisco UCSM
  block:
    - name: Get Device Connector Status
      uri:
        url: "https://{{ inventory_hostname }}/connector/Systems"
        method: GET
        headers:
          Content-Type: application/json
          ucsmcookie: "ucsm-cookie={{ hostvars['DUMMY_HOST']['ucsm_cookie'] }}"
        return_content: yes
        validate_certs: no
      register: get_device_connector_state_response
      delegate_to: local_host
      tags: 
        - get_device_connector_state
      # - never

    # (Option-1)
    - name: Save Device Connector Status
      ansible.builtin.set_fact:
        device_connector_status: "{{ get_device_connector_state_response.json[0].AccountOwnershipState }}"

    # (Option-2)
    - name: Register dummy host with variable 
      add_host:
        name: "DUMMY_HOST"
        device_connector_status: "{{ get_device_connector_state_response.json[0].AccountOwnershipState }}"

    - debug: 
        msg: "Device Connector Status on Cisco UCSM is: {{ device_connector_status }}"

      # NOT useful here    
    # - name: Print all available Ansible facts
    #   ansible.builtin.debug:
    #     var: ansible_facts