---

- name: Define anchor for ACI API login info
  block:
    - set_fact:
        aci_api_login_info: &aci_api_login_info
          hostname:             "{{ inventory_hostname }}"
          username:             "{{ apic_username }}"
          password:             "{{ apic_password }}"
          use_proxy:            "{{ apic_use_proxy | default(false) }}"
          use_ssl:              "{{ apic_use_ssl | default(true) }}"
          validate_certs:       "{{ apic_validate_certs | default(false) }}"


    - debug:
        msg: "API Info is: {{ aci_api_login_info }}"
      tags: [never, debug]

    - debug:
        msg: "Debug Info is: {{ infra_hx_hc_cl3[3] }}"

- name: Task 04 - Create Application Profiles
  cisco.aci.aci_ap:
    <<: *aci_api_login_info
    annotation: orchestrator:ansible
    tenant:       "{{ infra_hx_hc_cl3[0].tenant.name }}"
    ap:           "{{ item.name }}"
    description:  "{{ item.description }}"
    state: present
  with_list:      "{{ infra_hx_hc_cl3[3].application_profiles}}"
  when: item.name is defined
  delegate_to: local_host
  tags: 
    - infra_application_profiles
    #- never