---
###########################################################################################
#
#  Configure tenant policies and profiles to enable connectivity to Cisco HyperFlex VSI
#
###########################################################################################


#----------------------------------------------------------------------------------------
#  To test only the tasks in this file, uncomment the info below to make the task a 
#  playbook and run the playbook using the name of this file. 
#----------------------------------------------------------------------------------------

  # - name: API Login to Cisco APIC 
  #   hosts: "{{ group | default('cisco_network_dc_fabric') }}"
  #   connection: local
  #   #gather_facts: no
  #   vars:
  #     aci_api_login_info: &aci_api_login_info
  #       hostname:         "{{ inventory_hostname }}"
  #       username:         "{{ apic_username }}"
  #       password:         "{{ apic_password }}"
  #       use_proxy:        "{{ apic_use_proxy | default(false) }}"
  #       validate_certs:   "{{ apic_validate_certs | default(false) }}"
  #     Dependencies: none
  #   tasks:
  #     - debug:
  #         msg: "API Info is: {{ intersight_api_login_info }}"
  #       tags: [never, debug]


  #-------------------------------------------------------------------------------------- 
  #   1. Create Tenant, VRF, BD, AP, EPG and Contracts. 
  #   2. Map EPG/VLAN to access layer VPC to HC-HXV cluster
  #--------------------------------------------------------------------------------------

      - name: Create Infra Tenant
        include_tasks: 021_aci_create_tenant.yml
        vars:
        tags: infra_tenant

      - name: Create Infra VRF
        include_tasks: 022_aci_create_vrf.yml
        vars:
        tags: infra_vrf

      - name: Create Infra Bridge Domains (BD)
        include_tasks: 023_aci_create_bridge_domains.yml
        vars:
        tags: infra_bridge_domains

      - name: Create Infra Application Profiles (AP)
        include_tasks: 024_aci_create_application_profiles.yml
        vars:
        tags: infra_application_profiles

      - name: Create Infra Endpoint Groups (EPGs)
        include_tasks: 025_aci_create_epgs.yml
        vars:
        tags: infra_epgs

      - name: Bind EPG to domain
        include_tasks: 026_aci_bind_epg_to_domain.yml
        vars:
        tags: infra_epgs_to_domain

      - name: Deploy EPG on VPC
        include_tasks: 027_aci_deploy_static_epg_on_vpc.yml
        vars:
        tags: infra_epgs_to_vpc

#--------------------------------------------------------------------------------------

